#! /bin/bash

xhost +

if [ -f ./radeontop-gui.v1 ]; then
	sudo ./radeontop-gui.v1

else if [ -f ./bin/Debug/radeontop-gui ]; then
	sudo ./bin/Debug/radeontop-gui
else
	sudo ./bin/Release/radeontop-gui
fi
fi

xhost -

